services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - '8080:8080'

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - '4200:80'

  my_database:
    image: postgres:17

    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
