// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiTasksByIdData, DeleteApiTasksByIdResponses, DeleteApiUsersByIdData, DeleteApiUsersByIdResponses, GetApiTasksByIdData, GetApiTasksByIdResponses, GetApiTasksData, GetApiTasksResponses, GetApiUsersByIdData, GetApiUsersByIdResponses, GetApiUsersData, GetApiUsersResponses, PostApiTasksData, PostApiTasksResponses, PostApiUsersData, PostApiUsersResponses, PutApiTasksByIdData, PutApiTasksByIdResponses, PutApiUsersByIdData, PutApiUsersByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getApiTasks = <ThrowOnError extends boolean = false>(options?: Options<GetApiTasksData, ThrowOnError>): RequestResult<GetApiTasksResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiTasksResponses, unknown, ThrowOnError>({ url: '/api/tasks', ...options });

export const postApiTasks = <ThrowOnError extends boolean = false>(options?: Options<PostApiTasksData, ThrowOnError>): RequestResult<PostApiTasksResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostApiTasksResponses, unknown, ThrowOnError>({
    url: '/api/tasks',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const deleteApiTasksById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiTasksByIdData, ThrowOnError>): RequestResult<DeleteApiTasksByIdResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteApiTasksByIdResponses, unknown, ThrowOnError>({ url: '/api/tasks/{id}', ...options });

export const getApiTasksById = <ThrowOnError extends boolean = false>(options: Options<GetApiTasksByIdData, ThrowOnError>): RequestResult<GetApiTasksByIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetApiTasksByIdResponses, unknown, ThrowOnError>({ url: '/api/tasks/{id}', ...options });

export const putApiTasksById = <ThrowOnError extends boolean = false>(options: Options<PutApiTasksByIdData, ThrowOnError>): RequestResult<PutApiTasksByIdResponses, unknown, ThrowOnError> => (options.client ?? client).put<PutApiTasksByIdResponses, unknown, ThrowOnError>({
    url: '/api/tasks/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiUsers = <ThrowOnError extends boolean = false>(options?: Options<GetApiUsersData, ThrowOnError>): RequestResult<GetApiUsersResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiUsersResponses, unknown, ThrowOnError>({ url: '/api/users', ...options });

export const postApiUsers = <ThrowOnError extends boolean = false>(options?: Options<PostApiUsersData, ThrowOnError>): RequestResult<PostApiUsersResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostApiUsersResponses, unknown, ThrowOnError>({
    url: '/api/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const deleteApiUsersById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiUsersByIdData, ThrowOnError>): RequestResult<DeleteApiUsersByIdResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteApiUsersByIdResponses, unknown, ThrowOnError>({ url: '/api/users/{id}', ...options });

export const getApiUsersById = <ThrowOnError extends boolean = false>(options: Options<GetApiUsersByIdData, ThrowOnError>): RequestResult<GetApiUsersByIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetApiUsersByIdResponses, unknown, ThrowOnError>({ url: '/api/users/{id}', ...options });

export const putApiUsersById = <ThrowOnError extends boolean = false>(options: Options<PutApiUsersByIdData, ThrowOnError>): RequestResult<PutApiUsersByIdResponses, unknown, ThrowOnError> => (options.client ?? client).put<PutApiUsersByIdResponses, unknown, ThrowOnError>({
    url: '/api/users/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
