// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5291' | (string & {});
};

export type CreateTaskDto = {
    title: string;
    userId?: string;
};

export type CreateUserDto = {
    name: string;
    email: string;
};

export type TaskDto = {
    id?: string;
    title?: string | null;
    completed?: boolean;
    userId?: string;
};

export type UpdateTaskDto = {
    title: string;
    completed?: boolean;
};

export type UpdateUserDto = {
    name: string;
    email: string;
};

export type UserDto = {
    id?: string;
    name?: string | null;
    email?: string | null;
};

export type GetApiTasksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tasks';
};

export type GetApiTasksResponses = {
    /**
     * OK
     */
    200: Array<TaskDto>;
};

export type GetApiTasksResponse = GetApiTasksResponses[keyof GetApiTasksResponses];

export type PostApiTasksData = {
    body?: CreateTaskDto;
    path?: never;
    query?: never;
    url: '/api/tasks';
};

export type PostApiTasksResponses = {
    /**
     * OK
     */
    200: TaskDto;
};

export type PostApiTasksResponse = PostApiTasksResponses[keyof PostApiTasksResponses];

export type DeleteApiTasksByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/tasks/{id}';
};

export type DeleteApiTasksByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiTasksByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/tasks/{id}';
};

export type GetApiTasksByIdResponses = {
    /**
     * OK
     */
    200: TaskDto;
};

export type GetApiTasksByIdResponse = GetApiTasksByIdResponses[keyof GetApiTasksByIdResponses];

export type PutApiTasksByIdData = {
    body?: UpdateTaskDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/tasks/{id}';
};

export type PutApiTasksByIdResponses = {
    /**
     * OK
     */
    200: TaskDto;
};

export type PutApiTasksByIdResponse = PutApiTasksByIdResponses[keyof PutApiTasksByIdResponses];

export type GetApiUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type GetApiUsersResponses = {
    /**
     * OK
     */
    200: Array<UserDto>;
};

export type GetApiUsersResponse = GetApiUsersResponses[keyof GetApiUsersResponses];

export type PostApiUsersData = {
    body?: CreateUserDto;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type PostApiUsersResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type PostApiUsersResponse = PostApiUsersResponses[keyof PostApiUsersResponses];

export type DeleteApiUsersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type DeleteApiUsersByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiUsersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type GetApiUsersByIdResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type GetApiUsersByIdResponse = GetApiUsersByIdResponses[keyof GetApiUsersByIdResponses];

export type PutApiUsersByIdData = {
    body?: UpdateUserDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type PutApiUsersByIdResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type PutApiUsersByIdResponse = PutApiUsersByIdResponses[keyof PutApiUsersByIdResponses];
